name: new_project
description: A Flutter app to store and display notifications.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0

  # For iOS-style icons
  cupertino_icons: ^1.0.8

  # To store notifications locally in SQLite
  sqflite: ^2.0.0+4

  # To get file paths to store the SQLite database
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
